#! /bin/bash


SERVER=mtw-flood-dbc
PORT=9017

#SERVER=mtw-flood-asc
#PORT=50025


#SERVER=mtw-flood-dbc;for((port=9017;port<=9017;++port));do echo -en "$port ";if echo -en "open $SERVER $port\nlogout\quit" | telnet 2>/dev/null | grep 'Connected to' > /dev/null;then echo -en "\n\nport $port/tcp is open\n\n";fi;done

for((port=9017;port<=9018;++port));do
   echo -en "$port "
   if echo -en "open $SERVER $port\nlogout\quit" | telnet 2>/dev/null | grep 'Connected to' > /dev/null; then
      echo -en "\n\nport $port/tcp is open\n\n"
   else
      echo -en "\n\nport $port/tcp is closed\n\n"
      ps -ef |grep telnet
   fi
done
