#! /bin/bash

DIR=/flood-releases/16.1.1/bundles
#BUNDLE=snocanl-sol10*.gz
BUNDLE=snocanlmed-sol10*.gz

####################################################
# NOTE that $USER's identity file is required, e.g.,
# set up host keys for authenticated ssh/scp login
#scp -P 23712 -i ~rb868x/.ssh/id_rsa rb868x@10.5.200.140:$DIR/$BUNDLE . 1>$VERSION 2>&1

scp -P 23712 -i ~rb868x/.ssh/id_rsa rb868x@10.5.200.140:$DIR/$BUNDLE . 1>/dev/null 2>&1
####################################################

for i in `ls $BUNDLE`; do
   sed -e "s/^NEWBUNDLE=.*.gz$/NEWBUNDLE=$i/g" <relbundles.list >relbundles.list.NEW
   cp relbundles.list.NEW relbundles.list
   rm relbundles.list.NEW
done 
