#! /bin/bash


#SERVER=mtw-flood-dbc
#PORT=9017

SERVER=mtw-flood-asc
PORT=50025
#PORT=50025999999999
CONNECTION=/tmp/CONNECTION

#HOST=mtw-flood-dbc;for((port=9017;port<=9019;++port));do echo -en "$port ";if echo -en "open $HOST $port\nlogout\quit" | telnet 2>/dev/null | grep 'Connected to' > /dev/null;then echo -en "\n\nport $port/tcp is open\n\n";fi;done

#telnet $SERVER $PORT&
#telnet $SERVER $PORT 1>/dev/null 2>&1&
#telnet $SERVER $PORT 1>/dev/null 2>&1 |grep "Connected to"&
#telnet $SERVER $PORT |grep "Connected to" 1>/dev/null 2>&1&
#telnet $SERVER $PORT |grep "Connected to" >$CONNECTION&

#telnet $SERVER $PORT& 1>$CONNECTION 2>&1
telnet $SERVER $PORT& 1>/dev/null 2>&1

#telnet $SERVER $PORT 1>$CONNECTION 2>&1
#telnet $SERVER $PORT 1>$CONNECTION 2>&1&
netstat -an |grep $PORT
#read "`telnet $SERVER $PORT&`" READ
#grep "Connected to" $CONNECTION

#if [[ -s $CONNECTION ]]; then
if [ $? -eq 0 ]; then
   echo $? --- 0 == SUCCESS
else
   echo $? --- !0 == FAIL
fi

kill -9 $! 1>/dev/null 2>&1
#rm $CONNECTION 1>/dev/null 2>&1
